### ISSUE TITLE
How can I connect from the outside to this proxy, for example through localhost

### ISSUE THREAD

**Issue by testinghere57564** [ilteoood/docker-surfshark#36]
Please help! Thank you!

**Comment by ilteoood** [comment]
You must provide enough informations to allow me to understand your context.
Do you have a compose file?
Which kind of proxy are you trying to use?

I've closed your previous issue for the same reasons: this is your last warning.
Next time I'll ban you.

**Comment by testinghere57564** [comment]
i'm trying to start your container with docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name CONT5A6I48NE8d -p 8211:8888 -p 9090:9090 -e SURFSHARK_USER= -e CREATE_TUN_DEVICE=yes -e SURFSHARK_PASSWORD= -v /etc/localtime:/etc/localtime:ro -v ovpn-data:/app/ovpn/config ilteoood/docker-surfshark . 
![image](https://user-images.githubusercontent.com/91505572/151660447-b6d6a7ef-9a1b-4f88-8bd3-789d55d39665.png)

Is this an example of success? As far as I know, the proxy is listening on port 8221. Accordingly, can I connect from outside http 127.0.0.1:8821 or does this container work differently?

**Comment by ilteoood** [comment]
The screenshot that you have posted here is correct, so your openvpn connection is up and running.

The container does not expose anything on port 8821, because this image contains only an openvpn client and not a proxy server.

If you want a proxy server, you should consider to use another container as sidecar.
