### ISSUE TITLE
docker compose.

### ISSUE THREAD

**Issue by riddertommie** [ilteoood/docker-surfshark#6]
I need some help connecting a container via docker-compose.

Any tips?

**Comment by ilteoood** [comment]
More detailed example provided:
https://github.com/ilteoood/docker-surfshark/blob/master/docker-compose.yml

**Comment by riddertommie** [comment]
thanks!!! going to take a look at it.

**Comment by riddertommie** [comment]
Sorry, i cant get i to work.

First i think with _command: -L 'https://ipinfo.io'_ you mean > _command: curl -L 'https://ipinfo.io'_ ????

but if i use below docker-compose gbittorrent keeps sending the term signal 

any tips help?

```
version:   "2"
--
 
services:
surfshark:
image: ilteoood/docker-surfshark
container_name: surfshark
environment:
- SURFSHARK_USER=user
- SURFSHARK_PASSWORD=pass
- SURFSHARK_COUNTRY=nl
- SURFSHARK_CITY=ams
- CONNECTION_TYPE=udp
cap_add:
- NET_ADMIN
devices:
- /dev/net/tun
ports:
- 7881:6881
- 7881:6881/udp
- 7080:8080
dns:
- 1.1.1.1
restart: unless-stopped
 
qbittorrent:
image: linuxserver/qbittorrent
container_name: qbittorrent
command: curl -L 'https://ipinfo.io'
depends_on:
- surfshark
network_mode: service:surfshark
environment:
- PUID=1000
- PGID=1000
- TZ=Europe/Amsterdam
- UMASK_SET=022
- WEBUI_PORT=8080
volumes:
- /opt/surfshark/qbit/config:/config
- /mnt/raid0/Torrents:/downloads
restart: unless-stopped
```

error log

[s6-finish] sending all processes the TERM signal.

**Comment by ilteoood** [comment]
"First i think with command: -L 'https://ipinfo.io' you mean > command: curl -L 'https://ipinfo.io' ????" -> No, the image inside the example compose expose curl as entrypoint, you just have to complete with the parameters in order to use it.

In my example, I've used the command entry just to show that after VPN connection, the public ip of the container will change.

You don't need that...
