### ISSUE TITLE
Unable to access local containers webui

### ISSUE THREAD

**Issue by jayantkaul** [ilteoood/docker-surfshark#79]
Hi there

I'm using the container as part of a portainer stack (attached) that also runs qbittorent and jackett.  Over the last few days I've been unable to access the webui for these apps. 

Could someone please give me some pointers? I haven't changed the scripts as such and I'm not sure why it stopped working.

[Stack - no username.txt](https://github.com/ilteoood/docker-surfshark/files/12693960/Stack.-.no.username.txt)

**Comment by jayantkaul** [comment]
I should add my local machine's IP is 192.168.0.199, so I've tried with Lan Network set to 192.168.0.0/24

**Comment by RickeyWard** [comment]
I have this issue too, no idea why it sometimes doesn't work

**Comment by ilteoood** [comment]
Could you provide more details so I can help you?

**Comment by RickeyWard** [comment]
It has something to do with the kill_switch functionality. instead of preventing my containers from reaching the internet it prevents them from being reached (they can still reach the internet as viewed from their logs) and the surfshark vpn log shows its successfully connected. I have lan network configured to match my local subnet 192.168.0.0/16. Restarting the stack a few times usually fixes it for a couple hours but then it dies again. (note that if I don't use ENABLE_KILL_SWTICH then my containers will leak out to internet unprotected until the vpn connects.

**Comment by ilteoood** [comment]
Do you have a script or a compose file to paste here?

**Comment by RickeyWard** [comment]
Upgrading to 1.7.2 from 1.7.0 seems to have fixed the issue where I lose connectivity from LAN. Thanks.
